Remove '--quiet' and '-q' options to git and wget

diff --git a/rpi-update b/rpi-update
--- a/rpi-update
+++ b/rpi-update
@@ -28,7 +28,7 @@ function update_self() {
 	echo "Performing self-update"
 	_tempFileName="$0.tmp"
 
-	if ! wget --quiet --output-document="${_tempFileName}" "${UPDATE_URI}"; then
+	if ! wget --output-document="${_tempFileName}" "${UPDATE_URI}"; then
 		echo "Failed to download update for rpi-update!"
 		echo "Make sure you have ca-certificates installed and that the time is set correctly"
 		exit 1
@@ -36,7 +36,7 @@ function update_self() {
 
 	OCTAL_MODE=$(stat -c '%a' "$0")
 	if ! chmod ${OCTAL_MODE} "${_tempFileName}" ; then
-  		echo "Failed: Error while trying to set mode on ${_tempFileName}"
+		echo "Failed: Error while trying to set mode on ${_tempFileName}"
 		exit 1
 	fi
 
@@ -107,7 +107,7 @@ function finalise {
 function download_repo {
 	echo "Setting up firmware (this will take a few minutes)"
 	mkdir -p "${FW_REPOLOCAL}"
-	git clone "${FW_REPO}" "${FW_REPOLOCAL}" --depth=1 --quiet
+	git clone "${FW_REPO}" "${FW_REPOLOCAL}" --depth=1
 	RETVAL=$?
 	if [[ ${RETVAL} -ne 0 ]]; then
 		echo "Failed to download new firmware files"
@@ -117,15 +117,15 @@ function download_repo {
 
 function update_repo {
 	echo "Updating firmware (this will take a few minutes)"
-	eval ${GITCMD} fetch --quiet
+	eval ${GITCMD} fetch
 	RETVAL=$?
 	if [[ ${RETVAL} -ne 0 ]]; then
 		echo "Failed to download updated firmware files"
 		exit 1
 	fi
-	eval ${GITCMD} reset --hard --quiet
-	eval ${GITCMD} clean -f -d --quiet
-	eval ${GITCMD} merge origin/master -m "automerge" --quiet
+	eval ${GITCMD} reset --hard
+	eval ${GITCMD} clean -f -d
+	eval ${GITCMD} merge origin/master -m "automerge"
 	RETVAL=$?
 	if [[ ${RETVAL} -ne 0 ]]; then
 		echo "Failed to download updated firmware files"
@@ -156,7 +156,7 @@ function do_update {
 function download_rev {
 	echo "Downloading specific firmware revision (this will take a few minutes)"
 	mkdir -p "${FW_REPOLOCAL}"
-	wget -q "${REPO_URI}/tarball/${FW_REV}" -O "${FW_REPOLOCAL}/${FW_REV}.tar.gz"
+	wget "${REPO_URI}/tarball/${FW_REV}" -O "${FW_REPOLOCAL}/${FW_REV}.tar.gz"
 	tar xzf "${FW_REPOLOCAL}/${FW_REV}.tar.gz" -C "${FW_REPOLOCAL}" --strip-components=1
 	rm "${FW_REPOLOCAL}/${FW_REV}.tar.gz"
 }
